# Generated by Django 2.2.15 on 2022-03-21 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('faculty', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('dsg-1', 'Assistant Professor'), ('dsg-2', 'Associate Professor')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='addr_corres',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address for corres'),
        ),
        migrations.AddField(
            model_name='account',
            name='addr_perm',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Address for permanent'),
        ),
        migrations.AddField(
            model_name='account',
            name='agp',
            field=models.IntegerField(blank=True, choices=[(None, 'Select'), (1, '6000'), (2, '7000'), (3, '8000'), (4, '9000'), (5, '10000')], null=True, verbose_name='AGP fig.'),
        ),
        migrations.AddField(
            model_name='account',
            name='catg',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('cast-1', 'SC'), ('cast-2', 'ST'), ('cast-3', 'OBC-A'), ('cast-4', 'OBC-B'), ('cast-5', 'GEN')], max_length=6, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='account',
            name='current_dsg',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Present Dsgn.'),
        ),
        migrations.AddField(
            model_name='account',
            name='dt_eligibility',
            field=models.DateField(blank=True, null=True, verbose_name='Date of promo elig'),
        ),
        migrations.AddField(
            model_name='account',
            name='dt_last_promo',
            field=models.DateField(blank=True, null=True, verbose_name='Date of last promotion'),
        ),
        migrations.AddField(
            model_name='account',
            name='dt_ob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='account',
            name='facult',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('fac-1', 'ARTS'), ('fac-2', 'SCIENCE'), ('fac-3', 'ENGINEERING'), ('fac-4', 'ISLM')], max_length=100, null=True, verbose_name='Faculty :'),
        ),
        migrations.AddField(
            model_name='account',
            name='from_dsg',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 1', 'Assistant Prof. (Stage 1)'), ('Stage 2', 'Assistant Prof. (Stage 2)'), ('Stage 3', 'Assistant Prof. (Stage 3)'), ('Stage 4', 'Associate Prof. (Stage 4)')], max_length=30, null=True, verbose_name='From stage/desgn.'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True, verbose_name='Gender(M/F)'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='highest_quali',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_carry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, default='Individual', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='parent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='general/pdfs/', verbose_name='Attachment(PDF)'),
        ),
        migrations.AddField(
            model_name='account',
            name='post',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 2', 'Assistant Prof. (Stage 2)'), ('Stage 3', 'Assistant Prof. (Stage 3)'), ('Stage 4', 'Associate Prof. (Stage 4)'), ('Stage 5', 'Professor (Stage 5)')], max_length=30, null=True, verbose_name='Post applied for'),
        ),
        migrations.AddField(
            model_name='account',
            name='quali_year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Qualifying Year'),
        ),
        migrations.AddField(
            model_name='account',
            name='to_dsg',
            field=models.CharField(blank=True, choices=[(None, 'Select Posts'), ('Stage 2', 'Assistant Prof. (Stage 2)'), ('Stage 3', 'Assistant Prof. (Stage 3)'), ('Stage 4', 'Associate Prof. (Stage 4)'), ('Stage 5', 'Professor (Stage 5)')], max_length=30, null=True, verbose_name='To stage/desgn.'),
        ),
        migrations.AddField(
            model_name='account',
            name='tot_experience',
            field=models.IntegerField(default=0, verbose_name='Total Experience in year'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateField(blank=True, null=True, verbose_name='Date of joining'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TeachingExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_class', models.IntegerField(blank=True, null=True, verbose_name='PG Classes')),
                ('ug_class', models.IntegerField(blank=True, null=True, verbose_name='UG Classes')),
                ('specialisation', models.CharField(blank=True, max_length=400, null=True, verbose_name='Specialisation under the Subject/Discipline')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='sts_after/pdfs/', verbose_name='Attachment(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Degree')),
                ('thesis', models.CharField(blank=True, max_length=500, null=True, verbose_name='Title of Dissertation/Thesis')),
                ('dt_award', models.DateField(blank=True, null=True, verbose_name='Date of Award')),
                ('institute', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Board/University')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='research/pdfs/', verbose_name='Attachment(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriorPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=400, null=True, verbose_name='Designation')),
                ('employer', models.CharField(blank=True, max_length=400, null=True, verbose_name='Name of Employer')),
                ('dt_join', models.DateField(blank=True, null=True, verbose_name='Date of Joining')),
                ('dt_leav', models.DateField(blank=True, null=True, verbose_name='Date of Leaving')),
                ('gross_salary', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gross Salary')),
                ('agp', models.IntegerField(blank=True, null=True, verbose_name='AGP/Payband')),
                ('reason_leaving', models.CharField(blank=True, max_length=400, null=True, verbose_name='Reason for Leaving')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='sts_before/pdfs/', verbose_name='Attachment(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PresentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, choices=[(None, 'Select'), ('Stage 1', 'Assistant Professor - Stage 1'), ('Stage 2', 'Assistant Professor - Stage 2'), ('Stage 3', 'Assistant Professor - Stage 3'), ('Stage 4', 'Assistant Professor - Stage 4'), ('Stage 5', 'Professor - Stage 5')], max_length=30, null=True, verbose_name='Designation')),
                ('period_from', models.DateField(blank=True, null=True, verbose_name='Period: from ')),
                ('period_to', models.DateField(blank=True, null=True, verbose_name='Period: to ')),
                ('pay_scale', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pay Scale')),
                ('agp', models.CharField(blank=True, choices=[(None, 'Select'), ('1st', '6000'), ('2nd', '7000'), ('3rd', '8000'), ('4th', '9000'), ('5th', '10000')], max_length=20, null=True, verbose_name='AGP fig.')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='sts_after/pdfs/', verbose_name='Attachment(PDF)')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Course')),
                ('place', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place')),
                ('duration', models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (No. of Weeks)')),
                ('period', models.CharField(blank=True, max_length=200, null=True, verbose_name='Place')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='orient/pdfs/', verbose_name='Attachment(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, default='Blank', max_length=200, null=True, verbose_name='Degree/Certificate')),
                ('name_board_university', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the Board/University')),
                ('year_passing', models.IntegerField(blank=True, null=True, verbose_name='Pass out(Yr.)')),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks (%)')),
                ('div_class_grade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Divn/Class/Grade')),
                ('subject', models.CharField(blank=True, max_length=500, null=True, verbose_name='Subject(s)')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='academy/pdfs/', verbose_name='Attachment(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='Department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Department'),
        ),
    ]
