# Generated by Django 2.2.15 on 2022-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220321_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_applicant',
            field=models.BooleanField(default=True),
        ),
    ]
