# Generated by Django 2.2.15 on 2022-03-30 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_is_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCatg_I',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direct_teaching', models.IntegerField(blank=True, null=True, verbose_name='Direct Teaching(self declaration)')),
                ('self_api_dt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_dt', models.FileField(blank=True, null=True, upload_to='api_catg1/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_dt', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('exam_duties', models.IntegerField(blank=True, null=True, verbose_name='Examination duties (question paper setting, Invigilation, evaluation of answer scripts etc.) (self declaration)')),
                ('self_api_ed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_ed', models.FileField(blank=True, null=True, upload_to='api_catg1/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_ed', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('innovating_teaching', models.IntegerField(blank=True, null=True, verbose_name='Innovative Teaching – learning methodologies, updating of subject contents/courses,mentoring etc.(self declaration)')),
                ('self_api_it', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_it', models.FileField(blank=True, null=True, upload_to='api_catg1/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_it', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
