# Generated by Django 2.2.15 on 2022-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220330_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicatg_i',
            name='actl_api_dt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AlterField(
            model_name='apicatg_i',
            name='direct_teaching',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours spent per academic year'),
        ),
    ]
