# Generated by Django 2.2.15 on 2022-04-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220331_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicatg_i',
            name='actl_api_ed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score'),
        ),
        migrations.AddField(
            model_name='apicatg_i',
            name='actl_api_it',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score'),
        ),
        migrations.AlterField(
            model_name='apicatg_i',
            name='actl_api_dt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score'),
        ),
    ]
