# Generated by Django 2.2.15 on 2022-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20220402_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='frm_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='frm_resubmission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='frm_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_dean',
            field=models.BooleanField(default=False, verbose_name='Are you Dean'),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_hod',
            field=models.BooleanField(default=False, verbose_name='Are you HOD'),
        ),
    ]
