# Generated by Django 2.2.15 on 2022-04-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220406_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='frm_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
