# Generated by Django 2.2.15 on 2022-04-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_frm_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='approved_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='frm_general_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='general_info_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='rejected_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='resubmission_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='submitted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
