# Generated by Django 2.2.15 on 2022-04-20 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220409_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCatg_II',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_based_activities', models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours spent per academic year')),
                ('actl_api_fba', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score')),
                ('self_api_fba', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_fba', models.FileField(blank=True, null=True, upload_to='api_catg2/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_fba', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('corp_life_management', models.IntegerField(blank=True, null=True, verbose_name='Hours spent per academic year')),
                ('actl_api_clm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score')),
                ('self_api_clm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_clm', models.FileField(blank=True, null=True, upload_to='api_catg2/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_clm', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('prof_dev_activity', models.IntegerField(blank=True, null=True, verbose_name='Hours spent per academic year')),
                ('actl_api_pda', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Actual Appraisal Score')),
                ('self_api_pda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Self Appraisal Score')),
                ('pdf_pda', models.FileField(blank=True, null=True, upload_to='api_catg2/pdfs/', verbose_name='Attachment(PDF)')),
                ('veri_api_pda', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
