# Generated by Django 2.2.15 on 2022-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_apicatg_ii'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='url_link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
    ]
