# Generated by Django 2.2.15 on 2022-06-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_research_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doc_link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document Link'),
        ),
    ]
