# Generated by Django 2.2.15 on 2022-06-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20220608_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicatg_i',
            old_name='url_link',
            new_name='url_dt',
        ),
        migrations.AddField(
            model_name='apicatg_i',
            name='url_ed',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
        migrations.AddField(
            model_name='apicatg_i',
            name='url_it',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
    ]
