# Generated by Django 2.2.15 on 2022-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20220609_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicatg_ii',
            old_name='url_link',
            new_name='url_clm',
        ),
        migrations.AddField(
            model_name='apicatg_ii',
            name='url_pda',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
    ]
