# Generated by Django 2.2.15 on 2022-06-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20220609_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicatg_ii',
            name='url_fba',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Put your document link'),
        ),
    ]
