# Generated by Django 2.2.15 on 2022-06-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_apicatg_ii_url_fba'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='doc_ref',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document ref'),
        ),
    ]
