# Generated by Django 2.2.15 on 2022-06-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_account_doc_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='doc_ref',
        ),
    ]
