# Generated by Django 2.2.15 on 2022-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_account_doc_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, choices=[(None, 'Select designation'), ('dsg-1', 'Assistant Professor'), ('dsg-2', 'Associate Professor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Select faculty'), ('fac-1', 'ARTS'), ('fac-2', 'SCIENCE'), ('fac-3', 'ENGINEERING'), ('fac-4', 'ISLM')], max_length=100, null=True, verbose_name='Faculty :'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select faculty'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True, verbose_name='Gender(M/F)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='highest_quali',
            field=models.CharField(blank=True, choices=[(None, 'Select qualification'), ('q1', 'Ph.D'), ('q2', 'M.phil'), ('q3', 'M.E'), ('q4', 'M.Tech'), ('q5', 'M.Arch'), ('q6', 'M.Pharm'), ('q7', 'M.Sc.'), ('q8', 'M.A'), ('q9', 'Others')], max_length=200, null=True),
        ),
    ]
