# Generated by Django 2.2.15 on 2022-06-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20220622_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='err_tag',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Error_Tag'),
        ),
    ]
