# Generated by Django 2.2.15 on 2022-07-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_account_err_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='err_tag',
        ),
        migrations.AddField(
            model_name='account',
            name='ass_yr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Assessment Year'),
        ),
    ]
