# Generated by Django 2.2.15 on 2022-07-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20220702_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='emp_id',
            field=models.CharField(default='000000', max_length=6, verbose_name='Emp_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orientation',
            name='period',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='From Date- To Date'),
        ),
    ]
