# Generated by Django 2.2.15 on 2022-07-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20220709_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_pwd',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='Designation',
            field=models.CharField(blank=True, choices=[(None, 'Select Designation'), ('dsg-1', 'Assistant Professor'), ('dsg-2', 'Associate Professor')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='agp',
            field=models.IntegerField(blank=True, choices=[(None, 'Select'), (1, '6000/10'), (2, '7000/11'), (3, '8000/12'), (4, '9000/13A'), (5, '10000/14')], null=True, verbose_name='AGP fig.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='catg',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('cast-1', 'SC'), ('cast-2', 'ST'), ('cast-3', 'OBC-A'), ('cast-4', 'OBC-B'), ('cast-4', 'OBC-B'), ('cast-5', 'GEN')], max_length=6, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emp_id',
            field=models.CharField(max_length=6, unique=True, verbose_name='Emp_id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='faculty',
            field=models.CharField(blank=True, choices=[(None, 'Select Faculty'), ('fac-1', 'ARTS'), ('fac-2', 'SCIENCE'), ('fac-3', 'ENGINEERING & TECHNOLOGY'), ('fac-4', 'ISLM')], max_length=100, null=True, verbose_name='Faculty :'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Select Faculty'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=6, null=True, verbose_name='Gender(M/F)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='highest_quali',
            field=models.CharField(blank=True, choices=[(None, 'Select Qualification'), ('q1', 'Ph.D'), ('q2', 'M.phil'), ('q3', 'M.E'), ('q4', 'M.Tech'), ('q5', 'M.Arch'), ('q6', 'M.Pharm'), ('q7', 'M.Sc.'), ('q8', 'M.A'), ('q9', 'Others')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='presentpost',
            name='agp',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('1st', '6000/10'), ('2nd', '7000/11'), ('3rd', '8000/12'), ('4th', '9000/13A'), ('5th', '10000/14')], max_length=30, null=True, verbose_name='AGP/Level'),
        ),
    ]
