# Generated by Django 2.2.15 on 2022-07-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20220709_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='emp_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Emp_id'),
        ),
    ]
