# Generated by Django 2.2.15 on 2022-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20220709_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pwd_link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document Link'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emp_id',
            field=models.CharField(max_length=6, unique=True, verbose_name='Emp_id'),
        ),
    ]
