# Generated by Django 2.2.15 on 2022-07-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20220710_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fwd_link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document Link'),
        ),
    ]
