# Generated by Django 2.2.15 on 2022-08-27 15:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_auto_20220728_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=account.models.get_image_path, verbose_name='Attachment(image)'),
        ),
    ]
