# Generated by Django 2.2.15 on 2022-04-24 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub_other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr_pub', models.PositiveIntegerField(blank=True, null=True, verbose_name='Year of Publication')),
                ('pub_type', models.CharField(blank=True, choices=[(None, 'Select'), ('TEXT_BK', 'Text Book'), ('REF_BK', 'Reference Book'), ('BK_CHAP', 'Book Chapter')], max_length=50, null=True, verbose_name='Role of Applicant')),
                ('chap_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Chapter')),
                ('bk_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Book')),
                ('no_auth', models.PositiveIntegerField(blank=True, null=True, verbose_name='No.of Authors')),
                ('name_pub', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Publisher')),
                ('sts_pub', models.CharField(blank=True, choices=[(None, 'Select'), ('INTL', 'International'), ('NATL', 'National'), ('LOCL', 'Local')], max_length=50, null=True, verbose_name='Status of Publisher')),
                ('isbn_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='ISBN/ISSN No.')),
                ('pub_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of the Publication/Book/Book chapter')),
                ('pub_pdf', models.FileField(blank=True, null=True, upload_to='pub_other/pdfs/', verbose_name='Upload Paper(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
