# Generated by Django 2.2.15 on 2022-04-24 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0003_auto_20220424_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cons_proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_app', models.CharField(blank=True, choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('fund_agnc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Funding Agency')),
                ('no_yrs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (no.of years)')),
                ('prj_amt', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amoun Mobilized (in Lkhs)')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of Document')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
