# Generated by Django 2.2.15 on 2022-04-24 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0004_cons_proj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prj_outcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_app', models.CharField(blank=True, choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('prj_type', models.CharField(blank=True, choices=[(None, 'Select'), ('MPD', 'Major Policy Document'), ('PTNT', 'Patent'), ('TETR', 'Technology Transfer'), ('PRDT', 'Product'), ('PRCS', 'Process')], max_length=50, null=True, verbose_name='Type of Project')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('prj_lvl', models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'Local'), ('CNGV', 'Central Govt'), ('STGV', 'State Govt')], max_length=50, null=True, verbose_name='Level')),
                ('ref_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='Document No./Patent No/Other reference no')),
                ('ptnt_sts', models.CharField(blank=True, choices=[(None, 'Select'), ('FILE', 'Filed'), ('PUBG', 'Published'), ('GRNT', 'Granted')], max_length=50, null=True, verbose_name='Patent Status')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of Document')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
