# Generated by Django 2.2.15 on 2022-04-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0005_prj_outcm'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrnl_pub',
            name='self_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='veri_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
    ]
