# Generated by Django 2.2.15 on 2022-04-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0006_auto_20220425_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20, null=True)),
                ('name_book', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
