# Generated by Django 2.2.15 on 2022-04-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0007_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrnl_pub',
            name='jrnl_pdf',
        ),
        migrations.AddField(
            model_name='jrnl_pub',
            name='jrnl_link',
            field=models.CharField(blank=True, max_length=700, null=True, verbose_name='Document Link'),
        ),
    ]
