# Generated by Django 2.2.15 on 2022-05-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0008_auto_20220430_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='jrnl_pub',
            name='jrnl_oth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Other's number"),
        ),
        migrations.AlterField(
            model_name='jrnl_pub',
            name='imp_fac',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Impact Factor (put 0 if NA)'),
        ),
    ]
