# Generated by Django 2.2.15 on 2022-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0009_auto_20220506_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='pub_other',
            name='self_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='pub_other',
            name='veri_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
    ]
