# Generated by Django 2.2.15 on 2022-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0010_auto_20220509_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='resch_proj',
            name='self_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='resch_proj',
            name='veri_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
    ]
