# Generated by Django 2.2.15 on 2022-05-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0011_auto_20220524_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='resch_proj',
            name='proj_tag',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Proj tile'),
        ),
        migrations.DeleteModel(
            name='Cons_proj',
        ),
    ]
