# Generated by Django 2.2.15 on 2022-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0012_auto_20220526_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='prj_outcm',
            name='self_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='prj_outcm',
            name='veri_api_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
    ]
