# Generated by Django 2.2.15 on 2022-05-30 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0013_auto_20220528_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resch_proj',
            name='prj_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Grant Sanctioned (in Lkhs)'),
        ),
        migrations.CreateModel(
            name='Resch_guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Student Name')),
                ('degree', models.CharField(blank=True, choices=[(None, 'Select'), ('MPHIL', 'Mphil'), ('ME', 'ME'), ('MTECH', 'Mtech'), ('PHD', 'PhD')], max_length=20, null=True, verbose_name='Degree')),
                ('title_thesis', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Thesis')),
                ('status', models.CharField(blank=True, choices=[(None, 'Select'), ('DEGR', 'Degree awarded'), ('THES', 'Thesis submitted')], max_length=50, null=True, verbose_name='Status')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
