# Generated by Django 2.2.15 on 2022-06-01 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0015_fellow_award'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_type', models.CharField(blank=True, choices=[(None, 'Select'), ('LECT', 'Invited Lecture'), ('PAPER', 'Paper presented')], max_length=50, null=True, verbose_name='Invitation Type')),
                ('title_lecture', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Lecture / Paper')),
                ('seminer', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name of the Conference/Seminar/ Workshop')),
                ('organizer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organized by')),
                ('venue', models.CharField(blank=True, max_length=300, null=True, verbose_name='Venue')),
                ('duration', models.CharField(blank=True, max_length=200, null=True, verbose_name='Duration')),
                ('prj_lvl', models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'State'), ('UNIV', 'University')], max_length=50, null=True, verbose_name='Level')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
