# Generated by Django 2.2.15 on 2022-06-01 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0016_lecture_paper'),
    ]

    operations = [
        migrations.CreateModel(
            name='E_Learning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the model')),
                ('course_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of the courses')),
                ('program_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='NAme of the programs')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Upload document')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
