# Generated by Django 2.2.15 on 2022-06-02 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0017_e_learning'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resch_cons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_tag', models.CharField(blank=True, max_length=5, null=True, verbose_name='Proj tile')),
                ('faculty_app', models.CharField(blank=True, choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], max_length=50, null=True, verbose_name='Area of the Applicant')),
                ('proj_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Title of the Project')),
                ('fund_agnc', models.CharField(blank=True, max_length=300, null=True, verbose_name='Funding Agency')),
                ('no_yrs', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duration (no.of years)')),
                ('prj_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Amount Mobilized(in Lkhs)')),
                ('prj_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link of the Grant Letter')),
                ('prj_pdf', models.FileField(blank=True, null=True, upload_to='resch_proj/pdfs/', verbose_name='Upload Grant Letter(PDF)')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
