# Generated by Django 2.2.15 on 2022-06-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0018_resch_cons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_outcm',
            name='ref_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document No./Patent No/Other reference no'),
        ),
        migrations.AlterField(
            model_name='resch_cons',
            name='prj_amt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Amount Mobilized (Rs.in Lacs)'),
        ),
    ]
