# Generated by Django 2.2.15 on 2022-06-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0020_auto_20220605_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resch_cons',
            name='faculty_app',
            field=models.CharField(choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], error_messages={'required': 'Please let us know what is your area of work!'}, max_length=50, null=True, verbose_name='Area of the Applicant'),
        ),
    ]
