# Generated by Django 2.2.15 on 2022-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0023_auto_20220606_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resch_cons',
            name='faculty_app',
            field=models.CharField(choices=[(None, 'Select'), ('ARTS', 'Arts'), ('SCNC', 'Science'), ('ENGG', 'Engineering & Technology')], error_messages={'blank': 'You must select an option!!!!! !', 'invalid': 'Wrong format.!!!!!'}, max_length=50, null=True, verbose_name='Area of the Applicant'),
        ),
    ]
