# Generated by Django 2.2.15 on 2022-07-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0025_auto_20220713_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resch_guide',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('DEGR', 'Degree awarded'), ('THES', 'Thesis submitted')], max_length=50, null=True, verbose_name='Status'),
        ),
    ]
