# Generated by Django 2.2.15 on 2022-07-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0027_auto_20220713_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jrnl_pub',
            name='imp_fac',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impact Factor (put 0 if NA)'),
            preserve_default=False,
        ),
    ]
