# Generated by Django 2.2.15 on 2022-07-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0029_auto_20220714_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_outcm',
            name='prj_lvl',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'Local'), ('CNGV', 'National(Central Govt)'), ('STGV', 'State Govt')], max_length=50, null=True, verbose_name='Level'),
        ),
    ]
