# Generated by Django 2.2.15 on 2022-08-18 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catg_3', '0030_auto_20220728_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prj_outcm',
            name='prj_lvl',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('INTR', 'International'), ('NATL', 'National'), ('LCL', 'Local'), ('CNGV', 'National (Central Govt.)'), ('STGV', 'State Govt.')], max_length=50, null=True, verbose_name='Level'),
        ),
        migrations.CreateModel(
            name='Api_summy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_catg', models.CharField(blank=True, max_length=5, null=True, verbose_name='API Category')),
                ('self_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score')),
                ('veri_api_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score')),
                ('api_sts', models.CharField(blank=True, max_length=50, null=True, verbose_name='API Status')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
