# Generated by Django 2.2.15 on 2022-08-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0031_auto_20220818_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_summy',
            old_name='api_catg',
            new_name='api_catg1',
        ),
        migrations.RenameField(
            model_name='api_summy',
            old_name='api_sts',
            new_name='api_sts1',
        ),
        migrations.RenameField(
            model_name='api_summy',
            old_name='self_api_score',
            new_name='self_api_score1',
        ),
        migrations.RenameField(
            model_name='api_summy',
            old_name='veri_api_score',
            new_name='veri_api_score1',
        ),
        migrations.AddField(
            model_name='api_summy',
            name='api_catg2',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='API Category'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='api_catg3',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='API Category'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='api_sts2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API Status'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='api_sts3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API Status'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='self_api_score2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='self_api_score3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Self Appraisal Score'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='veri_api_score2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
        migrations.AddField(
            model_name='api_summy',
            name='veri_api_score3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Verified API Score'),
        ),
    ]
