# Generated by Django 2.2.15 on 2022-08-21 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catg_3', '0032_auto_20220818_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Api_summy',
        ),
    ]
